#!/bin/bash

ORIGINAL_CONFIG_FILE="/etc/dolos.cfg_original"
CONFIG_FILE="/media/card/dolos.cfg"
OSSEC_AGENT_CONFIG="/tmp/ossec/ossec.conf"

OSSEC_SERVER=$(awk -F"=" '/^OSSEC_SERVER/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)
AGENT_KEY=$(awk -F"=" '/^AGENT_KEY/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)
IP_MODE=$(awk -F"=" '/^IP_MODE/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)
IP_ADDRESS=$(awk -F"=" '/^IP_ADDRESS/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)
IP_BROADCAST=$(awk -F"=" '/^IP_BROADCAST/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)
IP_NETMASK=$(awk -F"=" '/^IP_NETMASK/{gsub(/ /, "", $0);print $2}' $CONFIG_FILE)

AGENT_CONF="
<ossec_config>\n
  <client>\n
    <server-ip>$OSSEC_SERVER</server-ip>\n
  </client>\n
  <localfile>\n
    <log_format>syslog</log_format>\n
    <location>/var/log/syslog</location>\n
  </localfile>\n
</ossec_config>\n"



case "$1" in
        start)
                echo -n "Parsing Dolos config and starting OSSEC: "
                echo $AGENT_CONF > $OSSEC_AGENT_CONFIG
                chown ossec:ossec $OSSEC_AGENT_CONFIG
                chmod 755 $OSSEC_AGENT_CONFIG

                if [ !-f /media/card/dolos.cfg_original  ]; then
                  cp $ORIGINAL_CONFIG_FILE /media/card/dolos.cfg_original
                fi
                yes | /tmp/ossec/bin/manage_agents -i $AGENT_KEY
                /tmp/ossec/bin/ossec-control start
                echo "."
                ;;
        stop)
                echo -n "Stopping Beeswarm instance"
                /tmp/ossec/bin/ossec-control stop
                echo "."
                ;;
        restart | force-reload)
                $0 stop
                sleep 2
                $0 start
                if [ "$?" != "0" ]; then
                        exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/beeswarm-dolos-init {start|stop|restart|force-reload}"
                exit 1
esac

exit 0



