#!/bin/bash

MEDIA_PATH="/mnt"

ORIGINAL_CONFIG_FILE="/etc/dolos_config/dolos.cfg_original"
OSSEC_SERVER_RULES_DIR="/etc/dolos_config/ossec_rules"
CONFIG_FILE=$MEDIA_PATH/dolos.cfg
OSSEC_AGENT_CONFIG="/tmp/ossec/etc/ossec.conf"
OSSEC_AGENT_KEY="/tmp/ossec/etc/client.keys"

OSSEC_SERVER=$(awk -F"=" '/^OSSEC_SERVER/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
AGENT_KEY=$(awk -F"=" '/^AGENT_KEY/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
IP_MODE=$(awk -F"=" '/^IP_MODE/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
IP_ADDRESS=$(awk -F"=" '/^IP_ADDRESS/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
IP_BROADCAST=$(awk -F"=" '/^IP_BROADCAST/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
IP_NETMASK=$(awk -F"=" '/^IP_NETMASK/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
IP_GATEWAY=$(awk -F"=" '/^IP_GATEWAY/{gsub(/^[ \t]+|[ \t]+$/,"", $0);print $2}' $CONFIG_FILE)
NAMESERVER=$(awk -F"=" '/^NAMESERVER/{gsub(/^[ \t]+|[ \t]+$/, "", $0);print $2}' $CONFIG_FILE)

AGENT_CONF="
<ossec_config>\n
  <client>\n
    <server-ip>$OSSEC_SERVER</server-ip>\n
  </client>\n
  <localfile>\n
    <log_format>syslog</log_format>\n
    <location>/var/log/syslog</location>\n
  </localfile>\n
</ossec_config>\n"

IP_STATIC_CONF="
auto lo\n
iface lo inet loopback \n
auto eth0\n
iface eth0 inet static\n
  address $IP_ADDRESS\n
  netmask $IP_NETMASK\n
  gateway $IP_GATEWAY\n
  broadcast $IP_BROADCAST"

RESOLV_CONF="
nameserver $NAMESERVER"

IP_DHCP_CONF="
auto lo\
iface lo inet loopback \n
auto eth0\n
iface eth0 inet dhcp\n"

case "$1" in
        start)
                echo -n "Parsing Dolos config and starting OSSEC: "
                if [ "$IP_MODE" == "STATIC" ]
                  then
                    echo -e $IP_STATIC_CONF > /etc/network/interfaces
                    echo -e $RESOLV_CONF > /etc/resolv.conf
                  else
                    echo -e $IP_DHCP_CONF > /etc/network/interfaces
                fi
                ifup -a
                echo -e $AGENT_CONF > $OSSEC_AGENT_CONFIG
                chown ossec:ossec $OSSEC_AGENT_CONFIG
                chmod 755 $OSSEC_AGENT_CONFIG

                echo -e $AGENT_KEY > $OSSEC_AGENT_KEY                           
                chown ossec:ossec $OSSEC_AGENT_KEY                              
                chmod 750 $OSSEC_AGENT_KEY  

                mkdir -p  "$MEDIA_PATH/ossec_rules"
                cp -rf $OSSEC_SERVER_RULES_DIR/* $MEDIA_PATH/ossec_rules

                cp $ORIGINAL_CONFIG_FILE $MEDIA_PATH/dolos.cfg_original
                yes | /tmp/ossec/bin/manage_agents -i $AGENT_KEY
                /tmp/ossec/bin/ossec-control start
                echo "."
                ;;
        stop)
                echo -n "Stopping Beeswarm instance"
                /tmp/ossec/bin/ossec-control stop
                echo "."
                ;;
        restart | force-reload)
                $0 stop
                sleep 2
                $0 start
                if [ "$?" != "0" ]; then
                        exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/beeswarm-dolos-init {start|stop|restart|force-reload}"
                exit 1
esac

exit 0



