#!/bin/sh

SERVER_WORK_PATH="/tmp/beeswarm/server"
SERVER_PID_FILE="/var/run/beeswarm-server.pid"

case "$1" in
	start)
                # TODO: Test if we have sqlite db...
		echo -n "Starting Beeswarm server instance: "
		start-stop-daemon -m --pidfile $SERVER_PID_FILE -c beeswarm:beeswarm -S -x beeswarm -- -v --no_webui --max_sessions 0 --workdir $SERVER_WORK_PATH
		echo "."
		;;
	stop)
		echo -n "Stopping Beeswarm instance"
		start-stop-daemon -K --pidfile $SERVER_PID_FILE -x beeswarm
		echo "."
		;;
	restart | force-reload)
		$0 stop
		sleep 2
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/beeswarm-bootstraped-server {start|stop|restart|force-reload}"
		exit 1 
esac

exit 0
